### ISSUE TITLE
Failing to find assemblies in Editor

### ISSUE THREAD

**Issue by reithegoat** [patchkit-net/patchkit-patcher-unity#123]
I opened PatchKit Patcher (ver Pre-Release 3.14.0) in Unity 2018.3.14 and I was greeted with two errors.
```
Assets/PatchKit Patcher/Scripts/AppData/Local/Pack1Unarchiver.cs(226,30): error CS0246: The type or namespace name `AesCryptoServiceProvider' could not be found. Are you missing an assembly reference?
```
```
Assets/PatchKit Patcher/Scripts/PatcherStatistics.cs(165,28): error CS7069: Reference to type `System.ComponentModel.INotifyPropertyChanging' claims it is defined assembly `System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089', but it could not be found
```

Note, .NET 3.5 is deprecated in the Editor.

**Comment by witcher112** [comment]
Hello @reithegoat 

Please try to see this document - https://github.com/patchkit-net/patchkit-patcher-unity/blob/master/Assets/PatchKit%20Patcher/ERROR_FIX.txt

It explains how to fix this issue.

Best regards,
Tomasz
