### ISSUE TITLE
Deadlock when opening project (.Net 4.x issue)

### ISSUE THREAD

**Issue by stavrohristo90** [patchkit-net/patchkit-patcher-unity#154]
The project goes into a deadlock when you try to open it by prompting that it doesn't support .Net 4.x and it has to switch back to 3.5
When you press OK as it prompts you and it closes it, it does not switch back to 3.5 resulting in a deadlock situation

**Comment by witcher112** [comment]
@stavrohristo90 which version of Unity are you using?

If possible, please stick to 2018.4.2f1

**Comment by stavrohristo90** [comment]
Yes it was an issue with 2019
Seems like it only works with 2018
All good now thanks :)


On 30 October 2020 at 7:05, Tomasz Jaworski <notifications@github.com> wrote:






@stavrohristo90 which version of Unity are you using?

If possible, please stick to 2018.4.2f1
