### ISSUE TITLE
'CancellationToken' is an ambiguous reference

### ISSUE THREAD

**Issue by extremepro999** [patchkit-net/patchkit-patcher-unity#163]
I opened the project in unity and it showed this error

> Assets\PatchKit Patcher\Scripts\AppUpdater\AppUpdater.cs(123,33): error CS0104: 'CancellationToken' is an ambiguous reference

 I cannot run or build the project so I am basically stuck. When clicking the error it leads me to line **124** of **AppUpdater.cs** which is a void, here is the code of it

```
public void VerifyFiles(CancellationToken cancellationToken)
        {
            Assert.MethodCalledOnlyOnce(ref _verifyFilesHasBeenCalled, "VerifyFiles");
            
            var appRepairer = new AppRepairer(Context, _status);
            appRepairer.CheckHashes = true;

            DebugLogger.Log("VerifyFiles.");
            
            if (!appRepairer.Perform(cancellationToken))
            {
                throw new CannotRepairDiskFilesException("Failed to validate/repair disk files");
            }
        }
```

**Comment by witcher112** [comment]
Hi,

Please make sure you're using Unity 2018.4.2f1, as it's the only one we support for patcher sources.

**Comment by extremepro999** [comment]
> Hi,
> 
> Please make sure you're using Unity 2018.4.2f1, as it's the only one we support for patcher sources.

Oh ok but do you plan on upgrading to 2019 and 2020 (LTS) versions it will make it easier for the community

**Comment by witcher112** [comment]
Currently, we don't have such plans as it would require switching to the new C# Scripting Backend.
