### ISSUE TITLE
SharpRaven.dll issue on building

### ISSUE THREAD

**Issue by Immudelki** [patchkit-net/patchkit-patcher-unity#25]
Using v3.8.0 release version on Unity 2017.3.f.3 fresh project.

Seemed to work well (only removing webplayer references from  PlatformRunner.cs, some #UNITY_5_OR_LOWER thingy needed there btw).

Until I tried to build winX86 scene.
I'm getting an issue on the following dll (that is definitely in the files) :

ArgumentException: The Assembly System.Configuration is referenced by SharpRaven ('Assets/PatchKit Patcher/Library/SharpRaven.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:156)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1 alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2 cache, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:162)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:196)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Dzejkop** [comment]
Hi,
Try changing the `API Compatibility Level` under `Edit / Project Settings / Player` to `.NET 2.0`.
That should fix it for you.

**Comment by Immudelki** [comment]
Really? I thought it was already like that on creating new projects with 2017. hm. I'll check tonight to confirm. Thanks!

**Comment by Immudelki** [comment]
Aah. not .net 2.0 subset ^^. 
Okay, it works. Thanks!

**Comment by witcher112** [comment]
Good to hear that! Enjoy!
