### ISSUE TITLE
Unable to change resolution

### ISSUE THREAD

**Issue by thesnipe789** [patchkit-net/patchkit-patcher-unity#44]
Hello !
I just downloaded the latest version of PatchKit for Unity but I have a problem with trying to change the resolution of the launcher.

Here is a screenshot of the launcher or I add a white rectangle for the test :
![screenshot1](https://user-images.githubusercontent.com/38591694/39087359-127d675c-45a0-11e8-95b2-33b2d4d85ea4.PNG)

Here is a screenshot of the launcher result when I build them :
![screenshot2](https://user-images.githubusercontent.com/38591694/39087360-129610cc-45a0-11e8-8ca9-46ff5bc6c472.PNG)

Here, as written in the documentation, I modify the resolution:
![screenshot3](https://user-images.githubusercontent.com/38591694/39087379-81573126-45a0-11e8-984c-a4158101fa08.PNG)

Thank you in advance for your answer.

Regars,

**Comment by witcher112** [comment]
Hello!

This is Unity issue - it is saving default resolution in the registry, and takes it every time from there. Please try to change the `Company/Product Name` (you can see them at the top of the settings that you posted) and rebuild the patcher. It should refresh your resolution to the one that you've set.

I hope that this will help you!
Please let us know if it works :)

**Comment by thesnipe789** [comment]
Hello !

Thank you for your reply !

Indeed the resolution is to change well by applying what you told me.

On the other hand my launcher does not open after having uploaded it on the site and having chosen it, it gives me this error "Launcher is experiencing issues, would you like to keep trying?".

Here is how I proceed:
- I changed the launcher on Unity
- I created a launcher on PatchKit and I uploaded the version and I published them
- After I create a game on PatchKit by selecting the option "custom patch" and I select my patch and I publish
- After doing everything I hit "Get Launcher" on the game page and when I open my launcher he tells me "Launcher is experiencing issues, would you like to keep trying?"

Even modifying on the game page "custom patcher" in default sa still does not work.

Would you have a solution to give me?

Thank you in advance for your help.

**Comment by genail** [comment]
@thesnipe789 
Hi there!

Please send me your application name and e-mail that you're using to access your account to support@patchkit.net. This seems to be a configuration issue.

**Comment by witcher112** [comment]
I'm closing the issue since it's not related to the patcher.
